### PR TITLE
Feature html mapping

### PR DESCRIPTION
**Pull request by abelpz**
Added html mapping feature as proposed by Arpit Jacob.

### CODE REVIEW

**Review by mvahowe — COMMENTED** [review]
I haven't run this yet but, looking at the map, I wonder if we might want to have an array of classes. This would mean that, for example, in the case of sequences, you could have a `sequence` class that is reused, and then maybe `sequence_main`, `sequence_introduction` etc.

**Review by mvahowe — COMMENTED** [review]
Also, is there a reason not to nest the maps some more? I would have thought that lookup would be easier if you had keys which were just the type pointing to objects that had keys that were just the subType. You could do the "subType only" option, as well as the default option, with a reserved key such as "*".

**Review by mvahowe — COMMENTED** [review]
So maybe something like this?
```
{
  "main": {
    "*": "section"
  },
  "paragraph": {
    "usfm:p": "p"
  },
  "*": {
    "verses": "sub",
    "*": "span"
  }
}
```

**Comment by arpitjacob** [comment]
This looks great @abelpz 

1. I was looking at the output and wondering if the content html tag is necessary as it seems redundant all? 

`<span class="content">nor</span>` 

2. for classname can we use standard css naming conventions `.this-is-example-classname`

**Comment by abelpz** [comment]
> So maybe something like this?
> 
> ```
> {
>   "main": {
>     "*": "section"
>   },
>   "paragraph": {
>     "usfm:p": "p",
>     "*": "div"
>   },
>   "*": {
>     "verses": "sub",
>     "*": "span"
>   }
> }
> ```

The way I did it should actually be pretty quick to look up, as I'm [generating the map keys in pef2html](https://github.com/unfoldingWord-box3/Epitelete-Perf-Html/blob/be1efcdcd33b4ae7214e596f6b796de96ccaaf41/src/helpers.js#L38) so accessing those should be O(1), but it is pretty ugly. 😅 I was looking to do something like what you proposed, it looks great, I'll try to implement it that way.

**Pull request merged**
